---
#Mappings:
#  RegionEC2InstanceImageMap:
#    us-east-1:
#      HVM64: ami-02c27944e9187fdb0

Parameters:
  ImageId:
    Description: AMI para la instancia EC2
    Type: AWS::EC2::Image::Id
    Default: ami-02c27944e9187fdb0

  EC2InstanceType:
    Description: Tipo de instancia para EC2
    Type: String
    Default: t2.small
  
  VpcId:
    Description: VPC donde trabajaran las instancias
    Type: AWS::EC2::VPC::Id
    Default: vpc-0737450a1b99a1593
  
  Subnet:
    Description: Subnets donde pueden ser creadas las instancias
    Type: AWS::EC2::Subnet::Id
    Default: subnet-0d7b725a72a17f794
    
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    DependsOn:
      - HTTPSecurityGroup
    Properties:
      SubnetId: !Ref Subnet
      ImageId:
        Ref: ImageId
      Tags:
        -
          Key: Name
          Value: EC2-ChallengeMeLi
      SecurityGroupIds:
      - Ref: HTTPSecurityGroup
      InstanceType:
        Ref: EC2InstanceType
      KeyName: 'privatekeyaorrego'
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt-get update
          sudo apt-get install python3-pip -y
          sudo apt-get install apt-transport-https ca-certificates curl gnupg lsb-release -y
          curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io -y
          sudo useradd -m -s /bin/bash dockerlabmeli
          sudo usermod -aG docker dockerlabmeli
          sudo passwd dockerlabmeli "Meli*2022."
          
#          su - dockerlabmeli

          
          
#          sudo apt-get install git -y
#          mkdir /tmp/meli
#          cd /tmp/meli
#          git clone https://github.com/aorrego17/challenge.git
#          sudo chmod +x ./install.sh
#          ./install.sh

  HTTPSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SG-ChallengeMeLi
      GroupDescription: Habilitar puerto 22 para administracion y 3000 para la API
      VpcId:
        Ref: VpcId
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        ToPort: 22
        IpProtocol: tcp
      - CidrIp: 0.0.0.0/0
        FromPort: 3000
        ToPort: 3000
        IpProtocol: tcp
