---
#Mappings:
#  RegionEC2InstanceImageMap:
#    us-east-1:
#      HVM64: ami-02c27944e9187fdb0

Parameters:
  ImageId:
    Description: AMI para la instancia EC2
    Type: AWS::EC2::Image::Id
    Default: ami-02c27944e9187fdb0

  EC2InstanceType:
    Description: Tipo de instancia para EC2
    Type: String
    Default: t2.small
  
  VpcId:
    Description: VPC donde trabajaran las instancias
    Type: AWS::EC2::VPC::Id
    Default: vpc-0737450a1b99a1593
  
  SubnetId:
    Description: Subnets donde pueden ser creadas las instancias
    Type: AWS::EC2::Subnet::Id
    Default: subnet-0d7b725a72a17f794
    
Resources:
  TekLoonTestInstance:
    Type: AWS::EC2::Instance
    Properties:
      #AvailabilityZone: us-east-1
      SubnetId:
        - !Ref SubnetId
      ImageId:
        - !Ref ImageId
        #- !Ref ImageId
        #- !Ref RegionEC2InstanceImageMap
        #- !Ref 'AWS::Region'
        #- HVM64
      Tags:
        -
          Key: Name
          Value: EC2-ChallengeMeLi
      InstanceType:
        - !Ref EC2InstanceType
      KeyName: 'privatekeyaorrego'
      SecurityGroups:
        - !Ref HTTPSecurityGroup
      #UserData:
      #  Fn::Base64: !Sub |
          #!/bin/bash
      #    sudo apt-get update
      #    sudo apt-get install python3-pip -y
      #    sudo apt-get install git -y
      #    mkdir /tmp/meli
      #    cd /tmp/meli
      #    git clone https://github.com/aorrego17/challenge.git
      #    sudo chmod +x ./install.sh
      #    ./install.sh

  HTTPSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SG-ChallengeMeLi
      GroupDescription: Habilitar puerto 22 para administracion desde un origen especifico
      VpcId:
        - !Ref VpcId
      SecurityGroupIngress:
      - CidrIp: 179.15.238.155/32
        FromPort: 22
        ToPort: 22
        IpProtocol: tcp
