---
Mappings:
  RegionEC2InstanceImageMap:
    us-east-1:
      HVM64: ami-02c27944e9187fdb0

Parameters:
  EC2InstanceType:
    Description: The Instance Type Chosen for EC2
    Type: String
    
Resources:
  TekLoonTestInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: !FindInMap
        - RegionEC2InstanceImageMap
        - !Ref 'AWS::Region'
        - HVM64
      Tags:
        -
          Key: Name
          Value: EC2-Challenge
      InstanceType: !Ref EC2InstanceType
      KeyName: 'privatekeyaorrego'
      SecurityGroups:
        - !Ref HTTPSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt-get update
          sudo apt-get install git
          y
          mkdir /meli
          cd /meli
          git clone https://github.com/aorrego17/challenge.git

  HTTPSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable port 80 and port 443
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80
      - CidrIp: 0.0.0.0/0
        FromPort: 443
        IpProtocol: tcp
        ToPort: 443
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
