---
#Mappings:
#  RegionEC2InstanceImageMap:
#    us-east-1:
#      HVM64: ami-02c27944e9187fdb0

Parameters:
  ImageId:
    Description: AMI para la instancia EC2
    Type: AWS::EC2::Image::Id
    Default: ami-02c27944e9187fdb0

  EC2InstanceType:
    Description: Tipo de instancia para EC2
    Type: String
    Default: t2.small
  
  VpcId:
    Description: VPC donde trabajaran las instancias
    Type: AWS::EC2::VPC::Id
    Default: vpc-0737450a1b99a1593
  
  Subnet:
    Description: Subnets donde pueden ser creadas las instancias
    Type: AWS::EC2::Subnet::Id
    Default: subnet-0d7b725a72a17f794
    
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    DependsOn:
      - HTTPSecurityGroup
      - AutomationServiceRole
    Properties:
      SubnetId: !Ref Subnet
      ImageId:
        Ref: ImageId
      Tags:
        -
          Key: Name
          Value: EC2-ChallengeMeLi
      SecurityGroupIds:
      - Ref: HTTPSecurityGroup
      InstanceType:
        Ref: EC2InstanceType
      KeyName: 'privatekeyaorrego'
      IamInstanceProfile: !Ref ManagedInstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt-get update -y
          mkdir /tmp/ssm-challengemeli
          cd /tmp/ssm-challengemeli
          wget https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/debian_amd64/amazon-ssm-agent.deb
          sudo dpkg -i amazon-ssm-agent.deb
          sudo apt-get update -y
          sudo apt-get install apt-transport-https ca-certificates curl gnupg lsb-release -y
          curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update -y
          sudo apt-get install docker-ce docker-ce-cli containerd.io -y
          sudo apt install -y curl wget
          curl -s https://api.github.com/repos/docker/compose/releases/latest | grep browser_download_url  | grep docker-compose-linux-x86_64 | cut -d '"' -f 4 | wget -qi -
          chmod +x docker-compose-linux-x86_64
          sudo mv docker-compose-linux-x86_64 /usr/local/bin/docker-compose
          sudo useradd -m -s /bin/bash dockerlabmeli
          sudo usermod -aG docker dockerlabmeli
          sudo passwd dockerlabmeli -d
          mkdir /tmp/challenge_MeLi
          cd /tmp/challenge_MeLi
          sudo apt-get install python3-pip -y
          sudo apt-get install git -y
          git clone https://github.com/aorrego17/challenge.git
          cd /tmp/challenge_MeLi/challenge/api_agente
          docker-compose up -d
          su - dockerlabmeli        
#          docker build -t agentemeli-linux .
#          docker build -t agente-challenge .
#          docker run agente-challenge


  HTTPSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SG-ChallengeMeLi
      GroupDescription: Habilitar puerto 22 para administracion y 3000 para la API
      VpcId:
        Ref: VpcId
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        ToPort: 22
        IpProtocol: tcp
      - CidrIp: 0.0.0.0/0
        FromPort: 3000
        ToPort: 3000
        IpProtocol: tcp

  AutomationServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ssm.amazonaws.com
            - ec2.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Path: "/"

  ManagedInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - !Ref AutomationServiceRole
      InstanceProfileName: ProfileChallengeMeLi
