version: '3'

networks:
  ambientedllo:
    driver: bridge

configs:
  httpd-config:
    external: true

services:
  agentemeli_linux:
    image: aorrego17/agentemeli_linux:v2
    restart: always
    networks:
      - ambientedllo
    ports:
      - "3000:3000"
